[project]
name = "ocr-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.26.0",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
]
